version: '3.9'
services:
  outerdb:
    container_name: outerdb
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=outer_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
